---
title: "correlation_plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(corrplot)
library(raster)
library(rgdal)

df<- read_csv("climate_data.csv")

df_all <- df %>% 
  select(cwd,ppt,tmn,tmx)

scr <- df %>% 
  filter(Island=="SCR") %>% 
  select(cwd,fog,ppt,tmn,tmx)

sri <- df %>% 
  filter(Island=="SRI") %>% 
  select(cwd,fog,ppt,tmn,tmx)

sca <- df %>% 
  filter(Island=="SCA") %>% 
  select(cwd,ppt,tmn,tmx)

scr_nofog <- df %>% 
  filter(Island=="SCR") %>% 
  select(cwd,ppt,tmn,tmx)

sri_nofog <- df %>% 
  filter(Island=="SRI") %>% 
  select(cwd,ppt,tmn,tmx)

scr_corr <- cor(scr, use = "complete.obs")
cor(sca, use = "complete.obs")
cor(sri, use = "complete.obs")
cor(df_all)

plot(scr)
```

```{r}
ppt <- raster("G:/working/claire/ClimateVariableAnalysis/hist_climate/ppt.tif")
tmx <- raster("G:/working/claire/ClimateVariableAnalysis/hist_climate/tmx.tif")
tmn <- raster("G:/working/claire/ClimateVariableAnalysis/hist_climate/tmn.tif")
cwd <- raster("G:/working/claire/ClimateVariableAnalysis/hist_climate/cwd.tif")

sri_ext <- readOGR("G:/working/claire/ClimateVariableAnalysis/hist_climate/sri_extent/sri_extent.shp")
sca_ext <- readOGR("G:/working/claire/ClimateVariableAnalysis/hist_climate/sca_extent/sca_extent.shp")
scr_ext <- readOGR("G:/working/claire/ClimateVariableAnalysis/hist_climate/scr_extent/scr_extent.shp")

summary(ppt)

ppt_df <- as.data.frame(ppt$ppt)

ggplot(ppt_df, aes(x=ppt))+
  geom_density(fill="lightblue", alpha=.5)+
  theme_classic()
```

