---
title: "MaxEnt Toolbox"
author: "Oakology"
date: "January 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Scenario Selection

```{r extent_selection}

#Change scenario- one thing to change throughout
scenario<-"allislands_270m"

#Options:
#allislands_270m
#ni_270m
#sca_270m
#sca_int_270m
#scr_270m
#sri_270m
#sri_adultyoung_270m
#sri_seedsap_270m
#scr_foginc_270m
#scr_fogdec_270m
#sri_foginc_270m
#sri_fogdec_270m
#MainlandCA

#Slope ones?
#Historic ranches?

#Make combine sections based on extents chosen because greatly differs-otherwise just have a lot of if else statements

```

Load Packages

```{r packages, message=FALSE}

#If packages missing use install.packages("packagename")
library(tidyverse)
library(sf)
library(raster)
library(sp)
library(rgdal)
library(tools)
#library(maptools)
#library(dismo)

```


Extent

```{r extent}

#Create scenario extent that will be used throughout the rest of the processes, based off the minimum BCM data available as well as the Channel Island CUSP outlines

#If else statements for scenarios: read in the correct data for each scenario
if (scenario=="allislands_270m"){
  #All Islands
  scenario_extent<-read_sf("G:/data/islands/all_islands/extent/allislandsoutline.shp")
  min_data<-raster("G:/data/climate/GISModel_Input/historic/cwd1981_2010_ave_HST_1539127145.tif")
}else if (scenario=="ni_270m"){
  #Northern Islands
  scenario_extent<-read_sf("G:/data/islands/all_islands/ni_outline/ni_outline.shp")
  min_data<-raster("G:/data/climate/GISModel_Input/historic/cwd1981_2010_ave_HST_1539127145.tif")
}else if (scenario=="scr_270m"|scenario=="scr_foginc_270m"|scenario=="scr_fogdec_270m"){
  #Santa Cruz
  scenario_extent<-read_sf("G:/data/islands/scr/scr_extent/scr_extent.shp")
  min_data<-raster("G:/data/climate/GISModel_Input/historic/cwd1981_2010_ave_HST_1539127145.tif")
}else if (scenario=="sri_270m"|scenario=="sri_adultyoung_270m"|scenario=="sri_seedsap_270m"|scenario=="sri_foginc_270m"|scenario=="sri_fogdec_270m"){
  #Santa Rosa
  scenario_extent<-read_sf("G:/data/islands/sri/sri_extent/sri_extent.shp")
  min_data<-raster("G:/data/climate/GISModel_Input/historic/cwd1981_2010_ave_HST_1539127145.tif")
}else if (scenario=="sca_270m"){
  #Santa Catalina
  scenario_extent<-read_sf("G:/data/islands/sca/sca_extent/sca_extent.shp")
  min_data<-raster("G:/data/climate/GISModel_Input/historic/cwd1981_2010_ave_HST_1539127145.tif")
}else if (scenario=="sca_int_270m"){
  #Santa Catalina Interpolated
  scenario_extent<-read_sf("G:/data/islands/sca/sca_extent/sca_extent.shp")
  min_data<-raster("G:/data/climate/GIS_Input_SCAInterpolated/historic/cwd1981_2010_ave_HST_1539127145.tif")
}else if (scenario=="MainlandCA"){
  #Mainland CA
  scenario_extent<-raster("G:/data/climate/GISModel_Input/historic/cwd1981_2010_ave_HST_1539127145.tif")
  min_data<-raster("G:/data/climate/GISModel_Input/historic/cwd1981_2010_ave_HST_1539127145.tif")
}else
  print ("No Scenario Selected")

cropped <- crop(min_data, extent(scenario_extent)) #Crop to extent of outlines
scen_extent <- mask(cropped, scenario_extent) #Mask to the exact island outline(s)
writeRaster(scen_extent, filename=paste0("G:/data/islands/MaxEnt/Extent/", scenario, ".tif"), overwrite=TRUE)#write extent raster

#Extent will be used throughout Script. Will call in the extent each time just to be careful.

```


Oak Combined and Individual ***Come back to this

```{r}
#Read in Oak Points
sca_oaks<-read_sf("G:/data/islands/sca/Quertome/SCAOakPoints_AEA.shp")
sca_xy<-st_coordinates(sca_oaks)
sri_oaks<-read_sf("G:/data/islands/sri/OakPoint/SRI_OakPoints_Updated.shp")
sri_xy<-st_coordinates(sri_oaks)
scr_oaks<-read_sf("G:/data/islands/scr/OakPoint/scr_calscape_oaks.shp")
scr_xy<-st_coordinates(scr_oaks)

#If else statements for scenarios: read in the correct data for each scenario
if (scenario=="allislands_270m"){
  #All Islands
  all_oaks<-rbind(sca_xy,sri_xy,scr_xy)
}else if (scenario=="ni_270m"){
  #Northern Islands
 all_oaks<-rbind(sri_xy,scr_xy)
}else if (scenario=="scr_270m"|scenario=="scr_foginc_270m"|scenario=="scr_fogdec_270m"){
  #Santa Cruz
all_oaks<-scr_xy
}else if (scenario=="sri_270m"|scenario=="sri_adultyoung_270m"|scenario=="sri_seedsap_270m"|scenario=="sri_foginc_270m"|scenario=="sri_fogdec_270m"){
  #Santa Rosa
all_oaks<-sri_xy
}else if (scenario=="sca_270m"){
  #Santa Catalina
all_oaks<-sca_xy
}else if (scenario=="sca_int_270m"){
  #Santa Catalina Interpolated
all_oaks<-sca_xy
}else if (scenario=="MainlandCA"){
  #Mainland CA
all_oaks<-rbind(sca_xy,sri_xy,scr_xy)
}else
  print ("No Scenario Selected")


alloaks<-as.data.frame(all_oaks)
alloaks$Species<-"Quercus tomentella"
Oaks<-alloaks[,c(3,1,2)]

#Export to csv


#OakWorkspace<-G:\data\islands\MaxEnt\MEInputOak\all_islands_100m
#OutputTable<-OakPoints.csv

#Save to Oak Workspace plus output table


#Also create options for oak points individuals

#comebine based on scenario

#Maybe for loop?

#if all islands then merge all three
#if north islands combine two
#If one island than that island
#if SRI subset then by the oak seed or sap category

```



Climate  
#Ran them all except for Mainland CA-issue with historic about extents

```{r}


if (scenario=="sca_int_270m"){
  #Santa Catalina Interpolated: Made by KrigingCatalina_AllBCM.Rmd
  clim_dirs<-list.dirs(path="G:/data/climate/GIS_Input_SCAInterpolated", full.names=F, recursive=F)
}else
clim_dirs<-list.dirs(path="G:/data/climate/GISModel_Input", full.names=T, recursive=F)

#Call in appropriate extent
scen_extent<-raster(paste0("G:/data/islands/MaxEnt/Extent/", scenario, ".tif"))
crs(scen_extent)<-CRS('+init=epsg:3310') 
 
for (clim in clim_dirs){
  #print (clim) #For loop through climate projections
  clim_vars<-list.files(clim, pattern='tif$', full.names=TRUE )
  for (var in clim_vars){
    #print (var)#For loop through climate variables
    clim_ras<-raster(var)
    crs(clim_ras)<-CRS('+init=epsg:3310')
    clim_crop <- crop(clim_ras, extent(scen_extent)) #Crop to extent of outlines
    climate <- mask(clim_crop, scen_extent) #Mask to the exact island outline(s)
    extent(climate)<-round(extent(climate),2)
    fn <- paste0("G:/data/climate/MEInput/", scenario, "/", basename(clim), "/", file_path_sans_ext(basename(var)), ".asc")
    writeRaster(climate,fn,format="ascii",overwrite=T)
  }#End for loop through climate variables
}#End for loop through climate projections


```



Island
#Need to finish up DEM issues, calculate slope and aspect, and then run all of these for each scenario 

```{r}

#For MainlandCA set this all to NULL

#Set final directory
island_fn<-paste0("G:/data/islands/MaxEnt/MEInput/", scenario, "/")
#Call in appropriate extent
scen_extent<-raster(paste0("G:/data/islands/MaxEnt/Extent/", scenario, ".tif"))
crs(scen_extent)<-CRS('+init=epsg:3310') 


#Soils
  soilshp<-read_sf("G:/data/islands/all_islands/Soil/soils_AEA.shp")
  ext<-extent(scen_extent)
  gridsize <- 270
  soilr <- raster(ext, res=gridsize)
  soilras <- rasterize(soilshp, soilr, field = 'MapUnit')
  crs(soilras)<-CRS('+init=epsg:3310')
  soil_crop <- crop(soilras, extent(scen_extent)) #Crop to extent of outlines
  soils <- mask(soil_crop, scen_extent) #Mask to the exact island outline(s)
  writeRaster(soils,paste0(island_fn, "soilclasses.asc"),format="ascii",overwrite=T)
  

  #Vegetation: Made by VegetationMapGrouping.Rmd
  #SCR
    scr_vegpshp<-read_sf("G:/data/islands/scr/SCRVegMapClass/SCRVegMapClass.shp")
    scr_vegr <- raster(extent(scen_extent), res=270)
    scr_vegras <- rasterize(scr_vegpshp, scr_vegr, field = 'Value')
    crs(scr_vegras)<-CRS('+init=epsg:3310')
  #NI
    ni_vegpshp<-read_sf("G:/data/islands/all_islands/Channel_Islands_Veg_Map_2017/NIVegMapClass/NIVegMapClass.shp")
    ni_vegr <- raster(extent(scen_extent), res=270)
    ni_vegras <- rasterize(ni_vegpshp, ni_vegr, field = 'Value')
    crs(ni_vegras)<-CRS('+init=epsg:3310')
  #SCA
    sca_vegpshp<-read_sf("G:/data/islands/sca/SCAVegMapClass/SCAVegMapClass.shp")
    sca_vegr <- raster(extent(scen_extent), res=270)
    sca_vegras <- rasterize(sca_vegpshp, sca_vegr, field = 'Value')
    crs(sca_vegras)<-CRS('+init=epsg:3310')
  #Merge to New Raster
    all_veg<-merge(scr_vegras, ni_vegras, sca_vegras)
    veg_crop <- crop(all_veg, extent(scen_extent)) #Crop to extent of outlines
    veg <- mask(veg_crop, scen_extent) #Mask to the exact island outline(s)
    writeRaster(veg,paste0(island_fn, "veg.asc"),format="ascii",overwrite=T)
    
    
#DEM THE STRUGGLE-Come back and fix
  ai_dem<-raster("G:/data/islands/all_islands/DEM/ai_dem270.tif")
  scr_dem<-raster("G:/data/islands/all_islands/DEM/scr_dem270.tif")
  sri_dem<-raster("G:/data/islands/all_islands/DEM/sri_dem270.tif")
  smi_dem<-raster("G:/data/islands/all_islands/DEM/smi_dem270.tif")
  sca_dem<-raster("G:/data/islands/sca/DEM/sca_dem_alb/sca_dem_alb270.tif")
  all_dem<-merge(ai_dem, scr_dem, sri_dem, smi_dem, sca_dem, tolerance=0.5)#Accepts different origins
  #all_dem<-raster("G:/data/islands/all_islands/DEM/all_dem270.tif") #Combined all DEMS at 270 in GIS with mosaic to new raster because much quicker and save across all projects
  crs(all_dem)<-CRS('+init=epsg:3310')
  #Figure out cropping and masking issue 
  dem_crop <- crop(all_dem, scen_extent) #Crop to extent of outlines
  dem <- mask(dem_crop, scen_extent) #Mask to the exact island outline(s)
  writeRaster(dem,paste0(island_fn, "DEM.asc"),format="ascii",overwrite=T)

  #Slope
  all_terrain<-terrain(all_dem, opt=c('slope', 'aspect'), unit='degrees')
  writeRaster(Slope,paste0(island_fn, "Slope.asc"),format="ascii",overwrite=T)
#Aspect
  writeRaster(Aspect,paste0(island_fn, "Aspect.asc"),format="ascii",overwrite=T)




```



Fog

```{r}

#Based on extent since only performing these for fog extent options

#Take fog layers-have to figure out how stored and how can for loop through
#Crop by extent
#Write asc raster for those fog options

#If else statements for scenarios: read in the correct data for each scenario
if (scenario=="scr_fog_270m"){
  #All Islands
  
}else if (scenario=="sri_fog_270m"|scenario=="sri_fog_adultyoung_270m"|scenario=="sri_fog_seedsap_270m"){
  #Santa Rosa

}else
  print ("No Fog Data Available")


SRI:
G:\data\tools\MaxEnt\Input\sri_100m_fog\historic\layers

SCR:
G:\data\tools\MaxEnt\Input\scr_100m_fog\historic\layer




```



Organization

```{r}

#Copy over code from BCM_organization but add in for all options made above but can select which of the variables actually should be carried over based on our decisions
#And based on scenario-some have fog and others dont and difference in oak points



```

